Feature/footer
paintedbirds/hoydonamos-web pull request #21
Opened 2022-02-26 18:28 UTC by rubenderigo

Add initial footer

2022-02-26 22:18 UTC, alejandroGonGon commented on src/features/common/layouts/MainLayout/MainLayout.js
> +import Footer from 'features/common/components/Footer/Footer';
Footer/Footer ??

2022-02-26 22:19 UTC, alejandroGonGon commented on src/layouts/MainLayout.js
> +import Footer from 'features/common/components/Footer/Footer';
🙄

2022-02-26 22:20 UTC, alejandroGonGon requested changes
Change the Footer to Index (imports)

2022-02-27 22:50 UTC, nicocadq approved these changes

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +  color: #bcbcbc;
This colors should come from the variables

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +  z-index: 999;
Should we add indexes to the variables?

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +    margin: 5px;
We are using rem in this project

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +  margin-bottom: 7px;
rem here

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +    height: 25px;
same about rems

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +    margin-right: 6px;
👀

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +    height: 20px;
👀

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +    margin: 20px 0;
Same here

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Footer/Footer.module.scss
> +    margin-bottom: 2px;
👀

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Header/Header.module.scss
>    box-shadow: 0px 4px 11px 0px #73b8b233;
I think that this should come from shadow variables

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Header/Header.module.scss
> +    max-width: 250px;
rem

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Header/Header.module.scss
>    border-radius: 14px;
add this to radius constants

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Header/Header.module.scss
> +    @apply lg:p-7 bg-white;
maybe we could use our own css here

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/Header/Header.module.scss
>      box-shadow: 0px 4px 11px 0px #73b8b233;
this should come from constatns

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/components/NotFound/NotFound.module.scss
>  @import '../../../../sass/variables';
```suggestion
@import 'sass/variables';
```

2022-02-27 22:50 UTC, nicocadq commented on src/features/common/layouts/Main/MainLayout.js
> +    <main className="my-8 max-w-screen-lg mx-auto w-full relative min-h-screen">
We should we add this into our own css

2022-02-27 22:50 UTC, nicocadq commented on src/index.css
> +  @apply bg-white w-full;
we could use our own css here

2022-02-27 22:50 UTC, nicocadq commented on src/pages/NotMatch/NotMatch.js
> +  <div className="m-auto">
👀

2022-02-27 22:50 UTC, nicocadq commented on src/sass/_variables.scss
> +$font-x-large: 20px;
Should we add this in rem?

2022-02-28 22:51 UTC, nicocadq approved these changes
try to take a look at the comments 🤙🏻

2022-02-28 22:51 UTC, nicocadq commented on src/features/common/layouts/Main/MainLayout.module.scss
> +  max-width: 64rem;
This should be into a variable

2022-02-28 22:51 UTC, nicocadq commented on src/sass/_variables.scss
> +$radius-full: 624.93rem;
I think that this values should be defined on px

2022-03-01 00:34 UTC, merged